version: '3.2'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd!"
# version: "3.2"
# services:

#   sql-server-db:
#     container_name: sql-server-db
#     image: microsoft/mssql-server-linux:2017-latest
#     ports:
#       - "1433:1433"
#     environment:
#       SA_PASSWORD: "P@ssw0rd!"
#       ACCEPT_EULA: "Y"