apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-${APP_SUBGROUP}
  labels:
    app: ${APP_NAME}-${APP_SUBGROUP}
    role: backend
    env: dev
  annotations:
    downscaler/uptime: Always
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ${APP_NAME}-${APP_SUBGROUP}
      role: backend
      env: dev
  template:
    metadata:
      labels:
        app: ${APP_NAME}-${APP_SUBGROUP}
        role: backend
        env: dev
    spec:
      nodeSelector:
        preemptible: "true"
      tolerations:
      - effect: NoSchedule
        key: type
        operator: Equal
        value: preemptible
      imagePullSecrets:
      - name: gitlab-auth
      containers:
      - name: ${APP_NAME}-${APP_SUBGROUP}
        image: ${IMAGE_TAG}
        imagePullPolicy: Always
        env:
        - name: CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              key: CONNECTION_STRING
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DB_PASSWORD
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: PIN_INTEGRATION_SIMULADO
          valueFrom:
            configMapKeyRef:
              key: PIN_INTEGRATION_SIMULADO
              name: ${APP_NAME}-${APP_SUBGROUP}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 130
          timeoutSeconds: 10
          failureThreshold: 10
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 100m 