apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-${APP_SUBGROUP}
data:
  CONNECTION_STRING: ${CONNECTION_STRING}
  DB_PASSWORD: ${DB_PASSWORD}
  PIN_INTEGRATION_SIMULADO: ${PIN_INTEGRATION_SIMULADO}
