apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-${APP_SUBGROUP}
data:      
  ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
  DATABASE_CONNECTION_STRING: ${DATABASE_CONNECTION_STRING}
  STORAGE_S3_BUCKET_NAME: ${STORAGE_S3_BUCKET_NAME}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  NOTIFICATIONS_MOCK: ${NOTIFICATIONS_MOCK}
  NOTIFICATIONS_BASE_URL: ${NOTIFICATIONS_BASE_URL}
  NOTIFICATIONS_CLIENT_ID: ${NOTIFICATIONS_CLIENT_ID}
  NOTIFICATIONS_CLIENT_SECRET: ${NOTIFICATIONS_CLIENT_SECRET}
  NOTIFICATIONS_GRANT_TYPE: ${NOTIFICATIONS_GRANT_TYPE}
  NOTIFICATIONS_AUTHENTICATION_KEY: ${NOTIFICATIONS_AUTHENTICATION_KEY}
  NOTIFICATIONS_FROM_NUMBER: ${NOTIFICATIONS_FROM_NUMBER}
  NOTIFICATIONS_GET_TOKEN: ${NOTIFICATIONS_GET_TOKEN}
  NOTIFICATIONS_SEND_API_URL: ${NOTIFICATIONS_SEND_API_URL}
  NOTIFICATIONS_GET_API_URL: ${NOTIFICATIONS_GET_API_URL}
  SECRET_JWT_TOKEN: ${SECRET_JWT_TOKEN}
