apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-${APP_SUBGROUP}
data:
  CONNECTION_STRING: ${CONNECTION_STRING}
  DB_HOST: ${DB_HOST}
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  PIN_INTEGRATION_SIMULADO: ${PIN_INTEGRATION_SIMULADO}
