apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-${APP_SUBGROUP}
  labels:
    app: ${APP_NAME}-${APP_SUBGROUP}
    role: backend
    env: dev
  annotations:
    downscaler/uptime: Always
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ${APP_NAME}-${APP_SUBGROUP}
      role: backend
      env: dev
  template:
    metadata:
      labels:
        app: ${APP_NAME}-${APP_SUBGROUP}
        role: backend
        env: dev
    spec:
      nodeSelector:
        preemptible: "true"
      tolerations:
      - effect: NoSchedule
        key: type
        operator: Equal
        value: preemptible
      imagePullSecrets:
      - name: gitlab-auth
      containers:
      - name: ${APP_NAME}-${APP_SUBGROUP}
        image: ${IMAGE_TAG}
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: ASPNETCORE_ENVIRONMENT
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: DATABASE_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              key: DATABASE_CONNECTION_STRING
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: STORAGE_S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              key: STORAGE_S3_BUCKET_NAME
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: AWS_DEFAULT_REGION
          valueFrom:
            configMapKeyRef:
              key: AWS_DEFAULT_REGION
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: NOTIFICATIONS_MOCK
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONS_MOCK
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: NOTIFICATIONS_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONS_BASE_URL
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: NOTIFICATIONS_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONS_CLIENT_ID
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: NOTIFICATIONS_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONS_CLIENT_SECRET
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: NOTIFICATIONS_GRANT_TYPE
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONS_GRANT_TYPE
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: NOTIFICATIONS_AUTHENTICATION_KEY
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONS_AUTHENTICATION_KEY
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: NOTIFICATIONS_FROM_NUMBER
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONS_FROM_NUMBER
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: NOTIFICATIONS_GET_TOKEN
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONS_GET_TOKEN
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: NOTIFICATIONS_SEND_API_URL
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONS_SEND_API_URL
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: NOTIFICATIONS_GET_API_URL
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONS_GET_API_URL
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: SECRET_JWT_TOKEN
          valueFrom:
            configMapKeyRef:
              key: SECRET_JWT_TOKEN
              name: ${APP_NAME}-${APP_SUBGROUP}
        - name: NOTIFICATIONS_MOCK_NUMBER
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONS_MOCK_NUMBER
              name: ${APP_NAME}-${APP_SUBGROUP}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 130
          timeoutSeconds: 10
          failureThreshold: 10
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
          limits:
            memory: 512Mi
            cpu: 1000m 